name: actiions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  actiions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18.x]
    defaults:
      run:
        working-directory: ./task

    steps:
      - uses: actions/checkout@v2
      - name: starting Node.js ${{matrix.node}}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: install dependencies
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: run linting
        run: npm run lint
